global using MediatR;
global using MediatR.Courier;
global using Serilog;
global using Serilog.Context;
global using System;
global using System.Collections.Generic;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;
