//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automaton.Studio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automaton.Studio.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must agree with Terms and Privacy Policy.
        /// </summary>
        public static string AgreeWithTermsPrivacyPolicy {
            get {
                return ResourceManager.GetString("AgreeWithTermsPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmtation is required.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed password must be the same as password.
        /// </summary>
        public static string ConfirmPasswordSameAsPassword {
            get {
                return ResourceManager.GetString("ConfirmPasswordSameAsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution failed.
        /// </summary>
        public static string CustomStepExecutionFailed {
            get {
                return ResourceManager.GetString("CustomStepExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom step name already exists.
        /// </summary>
        public static string CustomStepNameExists {
            get {
                return ResourceManager.GetString("CustomStepNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom steps list could not be loaded.
        /// </summary>
        public static string CustomStepsListNotLoaded {
            get {
                return ResourceManager.GetString("CustomStepsListNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom step update failed.
        /// </summary>
        public static string CustomStepUpdateFailed {
            get {
                return ResourceManager.GetString("CustomStepUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition name already exists.
        /// </summary>
        public static string DefinitionNameExists {
            get {
                return ResourceManager.GetString("DefinitionNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name is required.
        /// </summary>
        public static string DisplayNameRequired {
            get {
                return ResourceManager.GetString("DisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow name already exists.
        /// </summary>
        public static string FlowNameExists {
            get {
                return ResourceManager.GetString("FlowNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow could not be created.
        /// </summary>
        public static string FlowNotCreated {
            get {
                return ResourceManager.GetString("FlowNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow is required.
        /// </summary>
        public static string FlowRequired {
            get {
                return ResourceManager.GetString("FlowRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow activity lists could not be loaded.
        /// </summary>
        public static string FlowsActivityNotLoaded {
            get {
                return ResourceManager.GetString("FlowsActivityNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow list could not be loaded.
        /// </summary>
        public static string FlowsListNotLoaded {
            get {
                return ResourceManager.GetString("FlowsListNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is required.
        /// </summary>
        public static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        public static string NameExists {
            get {
                return ResourceManager.GetString("NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required.
        /// </summary>
        public static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is required.
        /// </summary>
        public static string OldPasswordRequired {
            get {
                return ResourceManager.GetString("OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner required to schedule flow.
        /// </summary>
        public static string RunnerRequiredToScheduleFlow {
            get {
                return ResourceManager.GetString("RunnerRequiredToScheduleFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong. Please contact support..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update user profile.
        /// </summary>
        public static string UserProfileUpdateFailed {
            get {
                return ResourceManager.GetString("UserProfileUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration failed.
        /// </summary>
        public static string UserRegistrationFailed {
            get {
                return ResourceManager.GetString("UserRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required.
        /// </summary>
        public static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
    }
}
