//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automaton.Studio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automaton.Studio.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Variable.
        /// </summary>
        internal static string AddVariable {
            get {
                return ResourceManager.GetString("AddVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition name.
        /// </summary>
        internal static string DefinitionName {
            get {
                return ResourceManager.GetString("DefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Flow.
        /// </summary>
        internal static string NewFlow {
            get {
                return ResourceManager.GetString("NewFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename workflow.
        /// </summary>
        internal static string RenameWorkflow {
            get {
                return ResourceManager.GetString("RenameWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step settings.
        /// </summary>
        internal static string StepSettings {
            get {
                return ResourceManager.GetString("StepSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        internal static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        internal static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Value.
        /// </summary>
        internal static string VariableValue {
            get {
                return ResourceManager.GetString("VariableValue", resourceCulture);
            }
        }
    }
}
